//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int IdPerson { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
