

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace proyecto.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class ProyectoLab3Entities : DbContext
{
    public ProyectoLab3Entities()
        : base("name=ProyectoLab3Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<Code> Codes { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Employer> Employers { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<SaleProduct> SaleProducts { get; set; }


    public virtual ObjectResult<reporte_ventas_Result> reporte_ventas(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
    {

        var fecha1Parameter = fecha1.HasValue ?
            new ObjectParameter("fecha1", fecha1) :
            new ObjectParameter("fecha1", typeof(System.DateTime));


        var fecha2Parameter = fecha2.HasValue ?
            new ObjectParameter("fecha2", fecha2) :
            new ObjectParameter("fecha2", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<reporte_ventas_Result>("reporte_ventas", fecha1Parameter, fecha2Parameter);
    }

}

}

