
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace proyecto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Person
{

    public int idPerson { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string email { get; set; }

    public string dress { get; set; }

    public string telephone { get; set; }

    public string sex { get; set; }

    public string documentNumber { get; set; }

    public int state { get; set; }

    public string type { get; set; }



    public virtual Client Client { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Employer Employer { get; set; }

}

}
