
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace proyecto.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sale
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sale()
    {

        this.SaleProducts = new HashSet<SaleProduct>();

    }


    public int IdSale { get; set; }

    public int idPerson { get; set; }

    public int idClient { get; set; }

    public int idProduct { get; set; }

    public decimal summary { get; set; }

    public System.DateTime saleDate { get; set; }

    public string saleNumber { get; set; }

    public int state { get; set; }



    public virtual Client Client { get; set; }

    public virtual Employer Employer { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SaleProduct> SaleProducts { get; set; }

}

}
